### PR TITLE
Update to new event API

### PR DESCRIPTION
**Pull request by wiibaa**
Meta issue => elastic/logstash#5309

also 
* use default travis.yml (https://github.com/elastic/logstash/issues/5811)
* add 'java' platform to gemspec (https://github.com/elastic/logstash/issues/5444)

### CODE REVIEW

**Comment by wiibaa** [comment]
travis is happy => @logstash-plugins/logstash-core ping for the review/merge

**Comment by breml** [comment]
LGTM

**Comment by wiibaa** [comment]
@breml sorry to forgot you as plugin maintainer

**Comment by breml** [comment]
@wiibaa no worries

**Pull request merged**
