### PR TITLE
CEF_EXT parsing

### PR DESCRIPTION
**Pull request by laf-rge**
I think you expect to have 2 strings, not 1. The current code fails since data is nil in the case of syslog.

### CODE REVIEW

**Comment by laf-rge** [comment]
Do you want me to remove the filter from the pull request?

**Comment by jsvd** [comment]
@laf-rge awesome! thanks for doing this. yes please, remove the filter

**Comment by laf-rge** [comment]
pulled changes from upstream and removed the filter.

**Comment by jsvd** [comment]
Just two minor things so we can merge:

1. `make tarball` no longer works to run and test plugins it's "bundle install && bundle exec rspec" so I guess we can remove the DEVELOPER.md file 

2. could you please go through the cef.rb and make sure the spacing indentation is 2 space based?

I think we're good to merge after this

**Comment by laf-rge** [comment]
resynchronized with upstream and whitespace format fixed with vim gg=G.

**Comment by jsvd** [comment]
LGTM
thanks for your work, this is a much requested codec :)

**Comment by jsvd** [comment]
One last thing, could you do the step 2 of the contribution guide ? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md

**Comment by laf-rge** [comment]
Completed

**Comment by jsvd** [comment]
Did you sign it with the same email as this patch? 
https://github.com/logstash-plugins/logstash-codec-cef/pull/2.patch

I'm getting an error on this side

**Comment by laf-rge** [comment]
Try again?

**Comment by jsvd** [comment]
Sorry to bother again with this but since the email on the patch differs from the one used to sign the CLA, we can't merge this. The email used in this PR is listed in https://github.com/logstash-plugins/logstash-codec-cef/pull/2.patch

**Comment by laf-rge** [comment]
Ok I carefully matched the caps this time. Hopefully that will work :)

**Comment by jsvd** [comment]
merged, thank you @laf-rge

**Pull request closed without merging**
