### PR TITLE
Fixes issue #62 - Changed agentHost field name to match CEF docs

### PR DESCRIPTION
**Pull request by n3g**
This commit fixes issue #62.
According to CEF documentation, the short name 'ahost' corresponds to 'agentHostName' and not 'agentHost' as it's being used now.

Note: this might have impact on code already using the incorrect mapping.

### CODE REVIEW

**Comment by kares** [comment]
Thanks Ricardo, this seems correct.
Checked the old v23 [documentation](https://www.secef.net/wp-content/uploads/sites/10/2017/04/CommonEventFormatv23.pdf), current is v25 and they both use *agentHostName*

**Comment by kares** [comment]
There should have been a failing spec with this change ... around
https://github.com/logstash-plugins/logstash-codec-cef/blob/master/spec/codecs/cef_spec.rb#L219
and
https://github.com/logstash-plugins/logstash-codec-cef/blob/master/spec/codecs/cef_spec.rb#L230
... since its testing with the old mapping.

CI did not run here so we're not seeing the :red_circle: here, could you please look at those?

**Comment by kares** [comment]
actually CI did run: https://travis-ci.org/logstash-plugins/logstash-codec-cef/builds/612443494

**Comment by elasticcla** [comment]
Hi @n3g, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/logstash-plugins/logstash-codec-cef/pull/75.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by elasticcla** [comment]
Hi @n3g, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/logstash-plugins/logstash-codec-cef/pull/75.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by n3g** [comment]
Hi @kares ,
Thanks for the warning, I didn't notice anything wrong as everything was green, but I think I've made the necessary changes in this last commit.

**Comment by colinsurprenant** [comment]
- This is somewhat of a duplicate for #45 which also includes other field fixes. I am ok in moving forward with this fix though. 
- I am unsure about version bump; looking at the changelog it seems we've allowed patch level bump for such a field name changes but to me this seems like a breaking change. Thoughts?

**Comment by kares** [comment]
did not see #45 ... should review the field updates, later. in terms of version lets do 6.1 (definitely not patch but inc minor)

**Comment by colinsurprenant** [comment]
@n3g would you be able to add a version bump + changelog commit?

**Comment by n3g** [comment]
@kares, @colinsurprenant: should I bump to 6.1.0 then? Current one is 6.0.1.

**Comment by colinsurprenant** [comment]
@n3g yes, bump to 6.1.0 and add to the `CHANGELOG`. Thanks!

**Comment by n3g** [comment]
There seems to be an error in the tests, but it's not related to the change. Any idea how to rerun this?

**Comment by colinsurprenant** [comment]
@ng3 restarted the build. LGTM pending green.

**Comment by colinsurprenant** [comment]
v6.1.0 published! 
Thanks for your contribution @n3g !

**Pull request merged**
