### PR TITLE
bump to version 5.0.6

### PR DESCRIPTION
**Pull request by colinsurprenant**
version 5.0.6 will include #51

### CODE REVIEW

**Comment by colinsurprenant** [comment]
🤦‍♂️ the doc. good catch @yaauie
Yeah, I'll add it here.

**Comment by colinsurprenant** [comment]
@yaauie added, LMK.

**Comment by yaauie** [comment]
One unaddressed comment about the changelog line. Other than that, LGTM.

**Comment by colinsurprenant** [comment]
v5.0.6 published. thanks @yaauie.

**Pull request merged**
