### PR TITLE
Update cef.rb

### PR DESCRIPTION
**Pull request by rmastro39**
screen shot 2017-06-07 at 11 33 29 am

Please see screenshot attached of the fields that were corrected and added.

Ruby Errors
 "ahost" => "agentHost"
 "dlat" => "destinationLatitude",
 "dlong" => "destinationLongitude",
 "dntdom" => "destinationNTDomain",
 "dtz" => "destinationTimeZone",
 "slat" => "sourceLatitude",
 "slong" => "sourceLongitude",

Ruby Corrections
agentHostName ahost
destinationGeoLatitude dlat
destinationGeoLongitude dlong
destinationNtDomain dntdom
deviceTimeZone dtz
sourceGeoLatitude slat
sourceGeoLongitude slong

CEF Not included in Ruby added
agentMacAddress amac
deviceMacAddress dvcmac
domainReferenceID domrid
domainID domid
domainURI domuri
domainExternalID domeid

### CODE REVIEW

**Comment by jordansissel** [comment]
@rmastro39 Looks like the CLA check failed, can you follow up on http://www.elasticsearch.org/contributor-agreement/ ?

**Comment by rmastro39** [comment]
@jordansissel Signed the CLA

**Comment by jordansissel** [comment]
@nich07as or @untergeek  - can you review this?

**Comment by jaredmcqueen** [comment]
Quick suggestion - it may be easier to separate the mappings / headers lines with line breaks so it'll be easier to see the difs.

**Comment by jordansissel** [comment]
@jaredmcqueen yeah agreed. That or move it to an external file that's easier to read/diff/maintain.

Reformatting doesn't need to happen in this PR, but we'll do it soon regardless.

**Comment by breml** [comment]
An other suggestion would be to order them alphabetically like they are ordered in [CommonEventFormatv23.pdf](https://community.saas.hpe.com/dcvta86296/attachments/dcvta86296/connector-documentation/1116/1/CommonEventFormatv23.pdf).

@rmastro39 The following CEF keys are not mentioned in the specification:

* domainReferenceID domrid
* domainID domid
* domainURI domuri
* domainExternalID domeid

Could you please provide your reference for those.

**Comment by breml** [comment]
@rmastro39 If there is no official reference for those, I am not sure, if we really should add them to the codec. But maybe we can add an config option, which allows the user to add his own mappings. What do you think?

**Comment by nich07as** [comment]
@breml - agree on the non-inclusion of undocumented fields for conciseness sake. As @jordansissel alluded to that plausibly moving to a separate config/file; it'd help with custom / undocumented fields that users might need. In the meantime, @rmastro39 - would you mind removing those undocumented fields? With that it LGTM. - Thanks!

**Comment by rmastro39** [comment]
@nich07as deleted undocumented fields and committed ; cheers

**Comment by breml** [comment]
@rmastro39: true, but the PR is currently not merge-able due to merge conflicts, which needs to be resolved first.
CC: @nich07as

**Comment by kares** [comment]
parts of these have been merged already, there's still unfinished pieces (some questionable - as they're not in the official docs). the PR could probably use a restart, let us know if someone is up for it.

**Comment by kares** [comment]
closing - no response

**Pull request closed without merging**
