### PR TITLE
Updated amac key translation to agentMacAddress per CEF documentation…

### PR DESCRIPTION
**Pull request by nich07as**
Updated amac key translation to agentMacAddress per CEF documentation (v23 p31)

### CODE REVIEW

**Comment by breml** [comment]
@nich07as can you please resolve the merge conflict.

**Comment by jordansissel** [comment]
Please rebase this before merging.

**Comment by nich07as** [comment]
@jordansissel - rebased; thanks for reviewing. ~N

**Comment by breml** [comment]
@nich07as Sorry to bother you again, could you please squash the 5 commits to one (or maybe 2) commits? Then we are ready for the merge.

**Comment by nich07as** [comment]
Made a blunder of my git, will resubmit a PR. Stay tuned @breml

**Pull request closed without merging**
