### PR TITLE
support keys with only two characters after the dot

### LINKED ISSUE #50: additional keys following name.sub where sub is 2 characters being missed
In CEF messages from a certain vendor, where the additional key value pairs follow a convention like ad.duration or ad.custom .. if that key is ad.nn it gets parsed as if its part of the last valid key. 

If you receive

`Dec 6 20:25:25 loghost CEF:0|Vendor|Device|Version|13|my message|5|dvchost=loghost cat=traffic deviceSeverity=notice ad.nn=TEST src=192.168.0.1 destinationPort=53 ... 
`
You end up with

`deviceSeverity => "notice ad.nn=TEST"`

in the parsed output.  This appears to occur with any x.y key value where the "y" is only two characters and  I can't seem to figure out where in the codec thats breaking.

### PR DESCRIPTION
**Pull request by jsvd**
attempt to fix #50

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by fpompermaier** [comment]
Why not this?

`EXTENSION_KEY_PATTERN = /(?:\w+(?:\.\w+)*(?==))/ `

This solution is more general since it takes into account also **a.b**=xxx or **a.b.c**=xxx or **a.b.c.d**=xxx and so on.

**Comment by xseris** [comment]
> Why not this?
> 
> `EXTENSION_KEY_PATTERN = /(?:\w+(?:\.\w+)*(?==))/ `
> 
> This solution is more general since it takes into account also **a.b**=xxx or **a.b.c**=xxx or **a.b.c.d**=xxx and so on.

or maybe this:

`EXTENSION_KEY_PATTERN = /(?:\w+(?:(\.){1}\w+)*?(?==))/`

 to avoid matching some word in strings containing more than one dot (with above solution a..b=c matches b)

**Comment by fpompermaier** [comment]
Any thoughts on the proposed patterns (wrt the one proposed in the PR)?

**Comment by jsvd** [comment]
@fpompermaier I have tried both patterns and they cause other tests to fail. because we use the key pattern to define the value pattern (as in "anything that doesn't look like a key"), it's really tricky to not break things with tiny regex changes

**Comment by guyboertje** [comment]
@jsvd 

I tested this pattern `EXTENSION_KEY_PATTERN = /(?:\w+(?:\.[^\|\s\.\=\\]+)?(?==))/` on Regex101 [here](https://regex101.com/r/UIJ7gE/1)
It occurred to me that in this section `[^\|\s\.\=\\]` we already exclude a space. If the first character of the section after the period must be a `\w` character then[ this is OK](https://regex101.com/r/U4schI/2) too `EXTENSION_KEY_PATTERN = /(?:\w+(?:\.\w[^\|\s\.\=\\]*)?(?==))/`

I forked the plugin, checked out your branch applied both patterns and the tests pass. WDYT?

**Comment by inqueue** [comment]
Can this PR be merged?

**Comment by colinsurprenant** [comment]
This has been replaced and fixed with #73 and v6.0.1 has been published.

**Pull request closed without merging**
